apiVersion: batch/v1
kind: Job
metadata:
  name: k6-demopnv
spec:
  backoffLimit: 0
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: k6-demopnv
      annotations:
        cluster-context: OCP4-SANDBOX-CLUSTER
        namespace: senarindam21-dev
    spec:
      initContainers:
      - name: git-clone
        image: image-registry.openshift-image-registry.svc:5000/senarindam21-dev/alpine:latest
        command: ['sh', '-c', 'sleep 30 && apk add --no-cache curl && curl -LO https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl && mv kubectl /usr/local/bin/ && while true; do sleep 3600; done && git clone -v --branch main https://TOKEN@github.com/senarindam21/K6-Perf.git /tmp']
        volumeMounts:
          - mountPath: /tmp
            readOnly: false
            name: git
        resources:
          requests:
            memory: 2G
            cpu: '2'
          limits:
            memory: 2G
            cpu: '2'
      containers:
      - name: k6-demopnv
        image: image-registry.openshift-image-registry.svc:5000/senarindam21-dev/k6-image:v0.53.0
        command: ['sh', '-c', 'k6 run /tmp/DemoService/main.js -e STEADYSTATE=5m -e scenario="LoadTest" -e ENV="qa"']
        volumeMounts:
          - mountPath: /tmp
            readOnly: false
            name: git
        resources:
          requests:
            memory: 1G
            cpu: '1'
          limits:
            memory: 2G
            cpu: '2'
      restartPolicy: Never
      volumes:
        - name: git
          emptyDir: {}
