apiVersion: batch/v1
kind: Job
metadata:
  name: k6-demopnv
spec:
  backoffLimit: 0
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: k6-demopnv
      annotations:
        cluster-context: OCP4-SANDBOX-CLUSTER
        namespace: senarindam21-dev
    spec:
      containers:
      - name: k6-demopnv
        image: image-registry.openshift-image-registry.svc:5000/senarindam21-dev/k6-image:v0.53.0
        command: ["sh", "-c", "while true; do sleep 30; done;"]
        volumeMounts:
          - mountPath: /tmp
            readOnly: false
            name: git
        resources:
          requests:
            memory: 1G
            cpu: '1'
          limits:
            memory: 2G
            cpu: '2'
      restartPolicy: Never
      volumes:
        - name: git
          emptyDir: {}
