name: Build and Execute K6 Tests on OpenShift

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Log in to OpenShift
      - name: Log in to OpenShift
        env:
          OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER_URL }}
          OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
        run: |
          oc login $OPENSHIFT_SERVER_URL --token=$OPENSHIFT_TOKEN --insecure-skip-tls-verify

      # Step 4: Log in to OpenShift internal registry
      - name: Log in to OpenShift internal registry
        run: |
          oc registry login --token=${{ secrets.OPENSHIFT_TOKEN }} --server=${{ secrets.OPENSHIFT_SERVER_URL }}

      # Step 8: Deploy and run the k6 test
      - name: Deploy and run k6 test
        run: |
          oc run k6-DemoService/main.js --image=$OPENSHIFT_REGISTRY/$PROJECT_NAME/$IMAGE_NAME:$IMAGE_TAG --restart=Never --attach=true --rm
