name: Build and Execute K6 Tests using GHA

on:
  push:
    branches:
      - main
    paths:
      - '**/openshift1.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    container:
      image: grafana/k6:0.53.0
      options: --user root

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Setup K6 
      #- name: Setup K6
      #  uses: grafana/setup-k6-action@v1

      # Step 3: Run K6 test
      - name: Run local k6 test
        run: k6 run DemoService/main.js --no-thresholds -e STEADYSTATE=1m -e scenario="LoadTest" -e ENV="qa"

      # Step 4: Monitor Runner CPU & Memory
      - name: Log CPU and Memory Usage (before)
        run: |
         echo "CPU and Memory usage before tests:"
         top -b -n 1 | head -20
         free -m
          
     # Update below timestamp to trigger the test
     # Test Start Time: 10:45 AM IST, June 17, 2025
