name: Build and Execute K6 Tests on OpenShift

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Log in to OpenShift
      - name: Log in to OpenShift
        env:
          OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER_URL }}
          OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
        run: |
          oc login https://api.sandbox-m3.1530.p1.openshiftapps.com:6443 --token=sha256~Bnf7eE6SdaUqlCLbqE6-_9dz6X2hr64hoHqEdYyGj6A

      # Step 4: Log in to OpenShift internal registry
      - name: Log in to OpenShift internal registry
        run: |
          oc registry login --token=sha256~Bnf7eE6SdaUqlCLbqE6-_9dz6X2hr64hoHqEdYyGj6A --server=https://api.sandbox-m3.1530.p1.openshiftapps.com:6443
      
      # Step 5 : Switching to Correct Openshift project namespace
      - name: Switch to OpenShift project
        env:
          OPENSHIFT_PROJECT: senarindam21-dev
        run: |
          oc project $OPENSHIFT_PROJECT
          
      # Step 6: Deploy and run the k6 test
      - name: Deploy and run k6 test
        run: |
          oc run k6 DemoService/main.js --image=image-registry.openshift-image-registry.svc:5000/senarindam21-dev/k6-image:v0.53.0 --restart=Never --attach=true --rm
