name: Build and Execute K6 Tests on OpenShift

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Log in to OpenShift
      - name: Log in to OpenShift
        env:
          OPENSHIFT_SERVER_URL: ${{ secrets.OPENSHIFT_SERVER_URL }}
          OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
        run: |
          oc login $OPENSHIFT_SERVER_URL --token=$OPENSHIFT_TOKEN

      # Step 3: Log in to OpenShift internal registry
      - name: Log in to OpenShift internal registry
        run: |
          oc registry login --token=$OPENSHIFT_TOKEN --server=$OPENSHIFT_SERVER_URL
      
      # Step 4 : Switching to Correct Openshift project namespace
      - name: Switch to OpenShift project
        env:
          OPENSHIFT_PROJECT: ${{ secrets.OPENSHIFT_PROJECT }}
        run: |
          oc project $OPENSHIFT_PROJECT
          
      # Step 5: Create the POD using YAML & Execute K6 test
      - name: Create the k6 test POD
        run: |
          oc apply -f ./k6-pod.yaml

      # Step 6: Capture POD name & Status & Apply Condition based on POD Status
      - name: Display POD name & Current Status
        run: |
          POD_NAME=$(oc get pods -o jsonpath='{.items[0].metadata.name}')
          echo "The Created POD is" $POD_NAME
          POD_STATUS=$(oc get pod $POD_NAME -o jsonpath='{.status.phase}')
          echo "Current POD status is" $POD_STATUS
          sleep 20
          if [ "$POD_STATUS" == "Pending" ]; then
          sleep 30
          fi
          if [ "$POD_STATUS" == "Failed" ]; then
          echo "Pod $POD_NAME has failed"
          fi
          while [[ "$POD_STATUS" == "Running" ]]; do
             POD_STATUS=$(oc get pod $POD_NAME -o jsonpath='{.status.phase}')
             echo "Test is in Progress with POD Status" $POD_STATUS
             sleep 30
          done
             echo "Test is Completed"
          
      # Step 7: Retrieve POD logs
      - name: Retrieve POD logs
        run: |
          mkdir -p logs
          POD_NAME=$(oc get pods -o jsonpath='{.items[0].metadata.name}')
          kubectl logs $POD_NAME > logs/pod.log

      # Step 8: Upload POD logs to Github
      - name: Upload POD logs
        uses: actions/upload-artifact@v4
        with:
          name: pod-logs
          path: logs/

      # Step 9: Delete Openshift Job
      - name: Delete OpenShift Job
        run: |
          oc delete job k6-demopnv
