name: Build and Execute K6 Tests using GHA

on:
  push:
    branches:
      - main
    paths:
      - '**/openshift1.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Setup K6
      - name: Setup K6
        uses: grafana/setup-k6-action@v1

      # Step 3: Run K6 test
      - name: Run local k6 test
        run: k6 run DemoService/main.js -e STEADYSTATE=3m -e scenario="LoadTest" -e ENV="qa"
          
     
