name: Build and Execute K6 Tests on OpenShift

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Log in to OpenShift
      - name: Log in to OpenShift
        env:
          OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER_URL }}
          OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
        run: |
          oc login https://api.sandbox-m3.1530.p1.openshiftapps.com:6443 --token=sha256~6ZrtXNwNIQ0zunbnb8uMVdJRPK1BQsGTwAPhPYCYDn0

      # Step 4: Log in to OpenShift internal registry
      - name: Log in to OpenShift internal registry
        run: |
          oc registry login --token=sha256~6ZrtXNwNIQ0zunbnb8uMVdJRPK1BQsGTwAPhPYCYDn0 --server=https://api.sandbox-m3.1530.p1.openshiftapps.com:6443
      
      # Step 5 : Switching to Correct Openshift project namespace
      - name: Switch to OpenShift project
        env:
          OPENSHIFT_PROJECT: senarindam21-dev
        run: |
          oc project $OPENSHIFT_PROJECT
          
      # Step 6: Create the POD using yaml & execute K6 test
      - name: Create the k6 test POD
        run: |
          oc apply -f ./k6-pod.yaml

      # Step 7: Capture the Created POD name
      - name: Display POD Name
        run: |
          POD_NAME=$(kubectl get pods -o jsonpath='{.items[0].metadata.name}')
          echo "The created pod name is " $POD_NAME
